language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t ridgerobinson/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ridgerobinson/docker-react npm run test